# SPDX-FileCopyrightText: 2026 SecPal Contributors
# SPDX-License-Identifier: CC0-1.0

[Unit]
Requires=secpal-postgresql-loopback.service
BindsTo=secpal-postgresql-loopback.service
After=secpal-postgresql-loopback.service postgresql.service
Wants=postgresql.service
